### ISSUE TITLE
Illegal use of FTDI drivers.

### ISSUE THREAD

**Issue by AnttiLukats** [OmriRaz/Kiwi-Project-Samples#4]
uLab Kiwi products also the Lite one use FTDI emulationt that forces the end user to use FTDI drivers with non-FTDI hardware what is in violation with FTDI drivers use License.

So FTDI can request this product to be cancelled.

**Comment by OmriRaz** [comment]
The Kiwi does not currently use FTDI drivers, nor FTDI hardware.
In the next revision of the board (in the  upcoming months), which will be available for purchase, will be based on different hardware due to other considerations and more features.

Best regards,
Omri
